title: MKForge
description: Development tools for LLM integration and workflow automation
url: https://mkforge.github.io
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
nav:
  - title: Documentation
    url: /docs
  - title: Releases
    url: /releases
  - title: GitHub
    url: https://github.com/mkforge/mkforge

# GitHub settings
github:
  is_project_page: true
  repository_url: https://github.com/mkforge/mkforge